### PR TITLE
[#EN-4332] Backported fix for leaked exception messages

### PR DESCRIPTION
**Pull request by rojlarge**

### CODE REVIEW

**Comment by jwbennet** [comment]
Are there no JSP changes for this?  I haven't looked at the changes closely but I know the reason for this fix is that the stacktrace is embedded in the HTML on the page so I was wondering if that was cleaned up as well?

**Comment by rojlarge** [comment]
Andy already backported that part of the fix in https://uisapp2.iu.edu/jira-prd/browse/EN-4468.

**Comment by jwbennet** [comment]
Cool, thanks for confirming!

**Review by jwbennet — APPROVED** [review]

**Comment by rojlarge** [comment]
No problem! Looks like we were just ahead of the curve. ;)

**Review by burnumd — APPROVED** [review]

**Pull request merged**
